### PR TITLE
Update to bevy 0.11

### PR DESCRIPTION
**Pull request by Luminoth**

### CODE REVIEW

**Comment by umut-sahin** [comment]
Thanks for the lovely PR @Luminoth!

Just one small request, could you split it in two commits with the following messages:
```
feat: bump bevy to v0.11
```
and
```
v0.3.0
```

Second commit should only include version bump in `Cargo.toml` (see https://github.com/umut-sahin/bevy-persistent/commit/a8b086f4589e55e3a68492edd8fceff256aa1237) and the first commit should contain everything else.

This is to have a consistent commit style (see https://github.com/umut-sahin/bevy-persistent/commits/main).

Once the PR is updated, I'll enable the CI, and then merge once the CI is green!

**Comment by umut-sahin** [comment]
Or maybe let's not bump to v0.3.0, I have a few things that I want to change. I'll apply those changes as well, bump to v0.3.0, and then do the release.

**Comment by Luminoth** [comment]
Yep, can do! Should be good to go without the crate version bump now.

**Comment by umut-sahin** [comment]
Could you please run:
```
git reset --soft HEAD~2 
git commit -m "feat: bump bevy to v0.11"
git push -f
```
in your branch please?

Then I'll run the CI and merge :+1:

**Comment by Luminoth** [comment]
Yep, should be good to go.

**Comment by umut-sahin** [comment]
Some WebAssembly tests are failing, could you update those as well?

(could you commit using `git commit --amend --no-edit` and then `git push -f` :relaxed:)

**Comment by umut-sahin** [comment]
Just realized, README needs updating as well :sweat_smile:

If it's too much, I can create a branch and apply the changes. Of course I'll set you as the commit author, and add you to Cargo.toml :wink:

**Comment by Luminoth** [comment]
Just making sure I'm on the same page - for both the wasm tests and the README, it's just the LControl KeyCode update?

**Comment by umut-sahin** [comment]
It seems to be the case, yes!

**Comment by umut-sahin** [comment]
For some reason CI isn't running :thinking: 

Also, there are conflicts with the new main after some changes I've made today :sleepy: 

Honestly, let me know if you want me to do the update and commit for you :stuck_out_tongue:

**Comment by Luminoth** [comment]
I'm good with whichever 😁 since we're hitting conflicts now it may be easier for you to patch it?

**Comment by umut-sahin** [comment]
I've created https://github.com/umut-sahin/bevy-persistent/pull/18 :partying_face: 

Let's continue from there!

**Pull request closed without merging**
