### PR TITLE
Update to 0.15.0

### PR DESCRIPTION
**Pull request by fallible-algebra**
Update the bevy version to 0.15.0-rc.1 and do a naive migration of `autosave.rs` over to a non-bundle approach.

### CODE REVIEW

**Comment by umut-sahin** [comment]
I want to wait until v0.15 is released. In the meantime, feel free to depend on https://github.com/fallible-algebra/bevy-persistent/commit/da97fa9e926423accd6e1af3944afd9d6a9c8c20 through git dependencies. I'll update the library to v0.15 and do a release as soon as I see v0.15 released.

**Comment by fallible-algebra** [comment]
Branch has been updated to 0.15.0.

**Review by umut-sahin — COMMENTED** [review]
Looks good to me, just one request, could you update the commit message to:
```
feat: bump bevy to v0.15
```

Then I'll run the CI, approve the PR, merge and do a new release!

**Comment by fallible-algebra** [comment]
Apologies for the hassle, I've reverted and squashed my commits now. let me know if there's anything else I need to do.

**Comment by umut-sahin** [comment]
Could you fix CI issues?

**Comment by umut-sahin** [comment]
Thanks for doing this BTW, I'll add you as an author before releasing the next version!

**Comment by fallible-algebra** [comment]
> Thanks for doing this BTW, I'll add you as an author before releasing the next version!

Of course, I needed it for my own project and the upgrade was mostly trivial.

On the CI: I've run cargo fmt, but I'm only getting the safari failure when running headless. The tests seem to run fine in safari when I open them in the interactive tests view. I'm not sure what to do there.

**Comment by umut-sahin** [comment]
Safari issue is fine, but conformance is still failing, and there are 12 files changes now :sweat_smile: 

I think you're not using nightly, which is required for some rustfmt overwrites.

If it's okay, I can create another PR to bring support, it'd be faster without going back and forth. I'll still add you as an author :wink:

**Comment by fallible-algebra** [comment]
yeah that seems like less hassle, apologies for the mess. didn't account for local machines being set to different toolchains.

**Comment by umut-sahin** [comment]
What's you e-mail? I need it for [authors section](https://github.com/umut-sahin/bevy-persistent/blob/ed617f183b57e4b4d3f4b4d57ea8321c09bf3aa8/Cargo.toml#L10).

**Comment by fallible-algebra** [comment]
> What's you e-mail? I need it for [authors section](https://github.com/umut-sahin/bevy-persistent/blob/ed617f183b57e4b4d3f4b4d57ea8321c09bf3aa8/Cargo.toml#L10).

`fallible.things@gmail.com`

**Comment by umut-sahin** [comment]
v0.7.0 is officially released on crates.io :partying_face:

**Pull request closed without merging**
